Problem Assignment 2

Experiment 2 - Numerical Python (Numpy)

In [56]:
import numpy as np

NORMALIZATION PROBLEM

In [68]:
X = np.random.random((5,5)) #this creates a 5x5 random array
X

array([[0.39521526, 0.82303184, 0.40086201, 0.0735523 , 0.38965276],
       [0.6666213 , 0.16485601, 0.11777189, 0.42659789, 0.23687161],
       [0.06894796, 0.77942194, 0.97830781, 0.37176023, 0.90330594],
       [0.11626867, 0.14840782, 0.34166952, 0.75574185, 0.60497596],
       [0.97285133, 0.15706332, 0.92961293, 0.77281409, 0.14372392]])

In [69]:
X = (X - X.mean()) / X.std() #will normalize the array and store it in variable X
X

array([[-0.23866889,  1.13408127, -0.22054997, -1.2708002 , -0.25651749],
       [ 0.63220124, -0.97783073, -1.12891124, -0.13797035, -0.74675176],
       [-1.2855743 ,  0.99414864,  1.63232074, -0.31392988,  1.3916596 ],
       [-1.13373467, -1.03060862, -0.41048301,  0.9181655 ,  0.43439766],
       [ 1.61481234, -1.00283542,  1.47607179,  0.97294579, -1.04563802]])

In [73]:
np.save("X_normalized.npy", X) #the normalized array will be save as X_normalized.npy

In [75]:
 #for double checking
print(result)

[[-0.23866889  1.13408127 -0.22054997 -1.2708002  -0.25651749]
 [ 0.63220124 -0.97783073 -1.12891124 -0.13797035 -0.74675176]
 [-1.2855743   0.99414864  1.63232074 -0.31392988  1.3916596 ]
 [-1.13373467 -1.03060862 -0.41048301  0.9181655   0.43439766]
 [ 1.61481234 -1.00283542  1.47607179  0.97294579 -1.04563802]]


DIVISIBLE BY 3 PROBLEM

In [61]:
#create an array where the values ranges from 1 to 100, each value is then squared
x = np.arange(1, 101)**2
x

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [62]:
x = x.reshape(10,10)
print(x)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [63]:
data = x[x % 3 == 0]
data

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [64]:
np.save("div_by_3.npy", data)

In [65]:
result = np.load("div_by_3.npy")
print(result)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
